### ISSUE TITLE
phonegap-push-plugin says it is not installed

### ISSUE THREAD

**Issue by Michazzz** [danielsogl/awesome-cordova-plugins#2297]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
After installation and configuration of this plugin, on the Chorme inspect tab, I can find warn log with informaiton: 

> Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.
pluginWarn @ main.js:58006

**Expected behavior:**
Successfull registration device by the plugin without warning about installation fail.

**Steps to reproduce:**
Install plugin step by step this introduction: [https://ionicframework.com/docs/native/push/](url) and insert necessary code into your application. Run application on real android  device and check the logs on Chrome inspect tab.

**Related code:**

```
  private pushInit() {
    let pushObject = this.push.init({
      android: {
        senderID: "xxxxxxxxxxxxx",
        sound: 'true',
        forceShow: true,
      },
      ios: {
        alert: 'true',
        badge: true,
        sound: 'false'
      }
    });

    pushObject.on('registration').subscribe((registration: any) => console.log('Device registered', registration));
  }
```

**Other information:**
You need to replace senderID: "xxxxxx" with the real sender ID. I created issue on the plugin github but it was closed as ionic issue. You can find this issue here: [https://github.com/phonegap/phonegap-plugin-push/issues/2169](url)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/michazzz/Repo/test-ionic/test-ionic-webapp/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.3.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v6.10.3
    npm               : 5.0.3 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/michazzz/Library/Android/sdk

Misc:

    backend : pro

```

**Comment by jtouceda** [comment]
Having the same trouble here.
The method "push.hasPermission()" enters the ".catch" case with the error "plugin_not_installed" because of that error.

**Comment by mateuspontesmoraes** [comment]
same problem

**Comment by vanessasoutoc** [comment]
same problem too

**Comment by vanessasoutoc** [comment]
@Michazzz, you resolved this problem?

**Comment by aneeskodappana** [comment]
@Michazzz @vanessasoutoc @mateuspontesmoraes 
are resolved this issue guys

**Comment by Michazzz** [comment]
@aneeskodappana @vanessasoutoc No, I didn't

**Comment by Oficina5** [comment]
Hi guys. I resolved problem install android 7.1.0 with comand
$ cordova platform  add android@7.1.0
and $ ionic cordova run android@7.1.0

**Comment by vanessasoutoc** [comment]
Hi guys. I resolved problem install android 7.1.0 with comand
$ cordova platform  add android@7.1.0
and $ ionic cordova run android@7.1.0

**Comment by FrancescoPaiola** [comment]
I have the same problem, can someone help me?
Here are my ionic infos:
```
Ionic:

   ionic (Ionic CLI)  : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 9 other plugins)

System:

   NodeJS : v9.10.1 (/usr/local/bin/node)
   npm    : 6.2.0
   OS     : macOS Mojave
```

and here my plugin list:

```
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.4.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-streaming-media 2.2.0 "StreamingMedia"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 2.0.0 "PushPlugin"
```
Updating Android version with the last Push plugin didn't solve this problem...  
I'm just going mad on this. :(

**Comment by FrancescoPaiola** [comment]
Unfortunately i found something here :'(
https://blog.phonegap.com/discontinuing-the-phonegap-push-service-540251bfc98
R.I.P.

**Comment by sdhupe19** [comment]
Try this
setTimeout(()=>{

       this.pushInit();
       
     }, 1000);
